#!/bin/bash

#stty -echo
#printf "Login: "
#read LOGIN
#stty echo
#printf "\n"
#
#stty -echo
#printf "Password: "
#read PASSWORD
#stty echo
#printf "\n"


#curl -L --max-redirs 1 --cookie-jar cookies.txt 'https://signin.intra.42.fr/users/sign_in' \
#  --data-raw 'utf8=%E2%9C%93&authenticity_token=4qEkTtUQLEDjHoqL%2BXTZH6aFXbgD4VhGO2mcSMu0ugvf0PzLE1Vm9gXWZjKcexKPqZwkBviJR8pCtFlBTHy7YQ%3D%3D&user%5Blogin%5D=smaccary&user%5Bpassword%5D=Jesuisnoelle3%408227&commit=Sign+in' \
#  --compressed
#

#cp cookies.txt coop.txt

rm coop.txt cookies.txt

curl --cookie-jar coop.txt 'https://signin.intra.42.fr/users/sign_in' \
  -H 'Connection: keep-alive' \
  -H 'Cache-Control: max-age=0' \
  -H 'Origin: https://signin.intra.42.fr' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'DNT: 1' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Referer: https://signin.intra.42.fr/users/sign_in' \
  -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Cookie: pro.id=bnVsbA%3D%3D--af7657a8234901541e1115b23c7a73d93a7191fd; user.id=bnVsbA%3D%3D--af7657a8234901541e1115b23c7a73d93a7191fd; _intra_42_session_production=688157b0b4cebd87ff081db8480cd8ac' \
  --data-raw 'utf8=%E2%9C%93&authenticity_token=i80ZXNZtDxrXTMKpzPtVSaPK2DFnBOBw%2Bd1x8%2BxADPk8r%2B%2FT8ganp0tUNIqTvk7x9pw1GkE0VYz9rBTvL7rLMA%3D%3D&user%5Blogin%5D=smaccary&user%5Bpassword%5D=Jesuisnoelle3%408227&commit=Sign+in' \
  --compressed

curl --cookie coop.txt --cookie-jar cookies.txt 'https://signin.intra.42.fr/' \
  --compressed

#curl --cookie-jar cookies.txt 'https://signin.intra.42.fr/' \
#  -H 'Cookie: _intra_42_session_production=f732ef966fcd4350309cfe8ca1f1ca2c' \
#  --compressed



# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.intra.42.fr	TRUE	/	FALSE	1599171781	_intra_42_session_production	f732ef966fcd4350309cfe8ca1f1ca2c
